### ISSUE TITLE
Change user-data for vmanage and vsmart to use eth0 for vpn512 and eth1 for vpn0

### ISSUE THREAD

**Issue by chrishocker** [CiscoDevNet/terraform-sdwan#3]

**Comment by jasonking3** [comment]
Current versions of the viptela VNFs place vpn512 interfaces in their own linux network namespace ('512').  Current versions of open-vm-tools only search the default namespace for IP addresses to report.  Therefore we cannot pull IP address information for vpn512 interfaces via terraform.  Unfortunately, this is not great for automation because it means we can't use vpn512 interfaces for automated config management (eg. ansible) without human involvement.

Closing this issue for now until something changes.
